# Generated by Django 3.2.16 on 2022-12-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_coupen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('applied', models.BooleanField(default=False)),
            ],
        ),
    ]
