# Generated by Django 3.2.16 on 2022-12-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221228_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='cno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
